name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: Set up AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=AKIAV5B2DUISHJQA22VA" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=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" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV


    - name: Run Pytest for edituserlist
      run: pytest ./edituserlist/test_lambda_edituser_list.py

    - name: Run Pytest for controljourney
      run: pytest ./controljourney/test_lambda_controlljourney.py

    - name: Run Pytest for configurestateparks
      run: pytest ./configurestateparks/test_lambda_configurestateparks.py

    - name: Run Pytest for finishjourney
      run: pytest ./finishjourney/test_lambda_finish_journey.py

    - name: Run Pytest for forgotpassword
      run: pytest ./forgotpassword/test_lambda_forgot_password.py

    - name: Run Pytest for getjourneys
      run: pytest ./getjourneys/test_lambda_getjourneys.py

    - name: Run Pytest for getnearestparks
      run: pytest ./getnearestparks/test_lambda_getnearestparks.py

    - name: Run Pytest for getreports
      run: pytest ./getreports/test_lambda_getreports.py

    - name: Run Pytest for getuserlist
      run: pytest ./getuserlist/test_lambda_getuserlist.py

    - name: Run Pytest for listparks
      run: pytest ./listparks/test_lambda_list_parks.py

    - name: Run Pytest for login
      run: pytest ./login/test_lambda_login.py

    - name: Run Pytest for resetpassword
      run: pytest ./resetpassword/test_lambda_resetpassword.py

    - name: Run Pytest for sendreports
      run: pytest ./sendreports/test_lambda_sendreports.py

    - name: Run Pytest for signup
      run: pytest ./signup/test_lambda_signup.py

    - name: Run Pytest for startjourney
      run: pytest ./startjourney/test_lambda_startjourney.py

    - name: Run Pytest for verifycode
      run: pytest ./verifycode/test_lambda.py
    
